name: Auth Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Auth dependencies
      run: npm ci
      working-directory: ./services/auth
      
    - name: Run Auth Tests
      run: npm test
      working-directory: ./services/auth

    - name: Install Gateway dependencies
      run: npm ci
      working-directory: ./gateway
      
    - name: Run Gateway Tests
      run: npm test
      working-directory: ./gateway

    - name: Install Catalog dependencies
      run: npm ci
      working-directory: ./services/catalog
      
    - name: Run Catalog Tests
      run: npm test
      working-directory: ./services/catalog

    - name: Install Cart dependencies
      run: npm ci
      working-directory: ./services/cart
      
    - name: Run Cart Tests
      run: npm test
      working-directory: ./services/cart
